import type { Metadata } from "next"

import { CatalogView } from "./catalog-view"

/* Everything Accura has, in one place, each with an ID to hand an agent.
   The data is catalog.json, generated by docs/machine-readable/build-catalog.mjs;
   rerun it after adding or renaming a component, story, pattern or template. */

export const metadata: Metadata = {
  title: "Catalog · Accura",
}

export default function CatalogPage() {
  return <CatalogView />
}
