// GENERATED by docs/machine-readable/build-catalog.mjs. Do not edit.
// Story modules keyed by catalog ID, so the catalog renders the same stories Storybook does.
import * as s0 from "@/stories/RecordRowAction.stories";
import * as s1 from "@/stories/Accordion.stories";
import * as s2 from "@/stories/Alert.stories";
import * as s3 from "@/stories/AlertDialog.stories";
import * as s4 from "@/stories/Avatar.stories";
import * as s5 from "@/stories/Badge.stories";
import * as s6 from "@/stories/Breadcrumb.stories";
import * as s7 from "@/stories/Button.stories";
import * as s8 from "@/stories/ButtonGroup.stories";
import * as s9 from "@/stories/Calendar.stories";
import * as s10 from "@/stories/Card.stories";
import * as s11 from "@/stories/Checkbox.stories";
import * as s12 from "@/stories/Combobox.stories";
import * as s13 from "@/stories/DatePicker.stories";
import * as s14 from "@/stories/Dialog.stories";
import * as s15 from "@/stories/Drawer.stories";
import * as s16 from "@/stories/Empty.stories";
import * as s17 from "@/stories/Input.stories";
import * as s18 from "@/stories/InputOTP.stories";
import * as s19 from "@/stories/Item.stories";
import * as s20 from "@/stories/Label.stories";
import * as s21 from "@/stories/NavigationMenu.stories";
import * as s22 from "@/stories/Pagination.stories";
import * as s23 from "@/stories/Progress.stories";
import * as s24 from "@/stories/RadioGroup.stories";
import * as s25 from "@/stories/Select.stories";
import * as s26 from "@/stories/Separator.stories";
import * as s27 from "@/stories/Sheet.stories";
import * as s28 from "@/stories/Sidebar.stories";
import * as s29 from "@/stories/Skeleton.stories";
import * as s30 from "@/stories/Slider.stories";
import * as s31 from "@/stories/Stepper.stories";
import * as s32 from "@/stories/Switch.stories";
import * as s33 from "@/stories/Table.stories";
import * as s34 from "@/stories/Tabs.stories";
import * as s35 from "@/stories/Textarea.stories";
import * as s36 from "@/stories/Toast.stories";
import * as s37 from "@/stories/Tooltip.stories";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const storyModules: Record<string, Record<string, any>> = {
  "acc-cmp-record-row-action": s0,
  "agt-cmp-accordion": s1,
  "agt-cmp-alert": s2,
  "agt-cmp-alert-dialog": s3,
  "agt-cmp-avatar": s4,
  "agt-cmp-badge": s5,
  "agt-cmp-breadcrumb": s6,
  "agt-cmp-button": s7,
  "agt-cmp-button-group": s8,
  "agt-cmp-calendar": s9,
  "agt-cmp-card": s10,
  "agt-cmp-checkbox": s11,
  "agt-cmp-combobox": s12,
  "agt-cmp-date-picker": s13,
  "agt-cmp-dialog": s14,
  "agt-cmp-drawer": s15,
  "agt-cmp-empty": s16,
  "agt-cmp-input": s17,
  "agt-cmp-input-otp": s18,
  "agt-cmp-item": s19,
  "agt-cmp-label": s20,
  "agt-cmp-navigation-menu": s21,
  "agt-cmp-pagination": s22,
  "agt-cmp-progress": s23,
  "agt-cmp-radio-group": s24,
  "agt-cmp-select": s25,
  "agt-cmp-separator": s26,
  "agt-cmp-sheet": s27,
  "agt-cmp-sidebar": s28,
  "agt-cmp-skeleton": s29,
  "agt-cmp-slider": s30,
  "agt-cmp-stepper": s31,
  "agt-cmp-switch": s32,
  "agt-cmp-table": s33,
  "agt-cmp-tabs": s34,
  "agt-cmp-textarea": s35,
  "agt-cmp-toast": s36,
  "agt-cmp-tooltip": s37,
};
